
[[constraint]]
  name = "github.com/Financial-Times/go-fthealth"
  version = "0.4.0"

[[constraint]]
  name = "github.com/Financial-Times/go-logger"
  version = "1.0.0"

[[constraint]]
  name = "github.com/Financial-Times/message-queue-go-producer"
  version = "0.2.0"

[[constraint]]
  name = "github.com/Financial-Times/service-status-go"
  version = "0.1.0"

[[constraint]]
  name = "github.com/Financial-Times/transactionid-utils-go"
  version = "0.2.0"

[[constraint]]
  name = "github.com/Financial-Times/uuid-utils-go"
  version = "1.0.1"

[[constraint]]
  name = "github.com/Workiva/go-datastructures"
  version = "1.0.43"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true
