apiVersion: v1
description: content-collection-unfolder Helm chart for Kubernetes
name: content-collection-unfolder
version: 0.0.0  # this entry can be left untouched as it is automatically handled by Jenkins pipeline
