# Values used for the deployed application.
replicaCount: 2
service:
  name: content-collection-unfolder
env:
  UNFOLDING_WHITELIST: content-package
  WRITER_URI: http://content-collection-rw-neo4j:8080/content-collection/
  WRITER_HEALTH_URI: http://content-collection-rw-neo4j:8080/__health
  CONTENT_RESOLVER_URI: http://document-store-api:8080/content/
  CONTENT_RESOLVER_HEALTH_URI: http://document-store-api:8080/__health
  CONTENT_COLLECTION_RELATIONS_URI: http://localhost:8080/__relations-api/contentcollection/{uuid}/relations
  Q_WRITE_TOPIC: PostPublicationEvents
